[project]
name = "ai-video-transcribe-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Abdullah Iftikhar", email = "abdullahiftikhar182006@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "google-genai>=1.0.0",
    "google-generativeai>=0.8.4",
    "google-search-results>=2.4.2",
    "groq>=0.18.0",
    "pydantic>=2.10.0",
    "python-dotenv>=1.0.1",
    "requests>=2.32.0",
    "rich>=13.9.0",
    "yt-dlp>=2025.1.15",
]

[project.scripts]
ai-video-transcribe-agent = "ai_video_transcribe_agent:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
