[theme]
base = "dark"
primaryColor = "#FF0000"
backgroundColor = "#0F0F0F"
secondaryBackgroundColor = "#181818"
textColor = "#F1F1F1"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
